import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:finvo/shared/utils/identicon.dart';

// Reference values generated by the server-side implementation
// (`server/app/utils/identicon.py`) for this seed — these tests pin the
// cross-language compatibility of the identicon algorithm.
const seed = '0d9f5ee4-2c9b-4c62-9db5-8c2b0b3761ab';

const expectedMatrix = [
  [true, true, false, true, true],
  [true, true, true, true, true],
  [false, true, false, true, false],
  [false, true, true, true, false],
  [true, false, false, false, true],
];

const expectedHue = 206.11764705882354;
const expectedRgb = (56, 104, 140);

void main() {
  group('cross-language compatibility with server/app/utils/identicon.py', () {
    test('matrix matches the Python implementation', () {
      expect(identiconMatrix(seed), expectedMatrix);
    });

    test('hue matches the Python implementation', () {
      expect(identiconHue(seed), closeTo(expectedHue, 1e-9));
    });

    test('foreground color matches the Python implementation', () {
      // Same formula the widget uses on light backgrounds:
      // HSV(hue, 0.60, 0.55), matching colorsys.hsv_to_rgb server-side.
      final color = HSVColor.fromAHSV(
        1.0,
        identiconHue(seed),
        0.60,
        0.55,
      ).toColor();
      // Compare the 0..1 color channels against the server's 0..255 ints,
      // allowing for the ±1 rounding each side applies at the boundary.
      expect(color.r, closeTo(expectedRgb.$1 / 255, 1 / 255));
      expect(color.g, closeTo(expectedRgb.$2 / 255, 1 / 255));
      expect(color.b, closeTo(expectedRgb.$3 / 255, 1 / 255));
    });
  });

  group('identicon properties', () {
    test('is deterministic', () {
      expect(identiconMatrix(seed), identiconMatrix(seed));
      expect(identiconHue(seed), identiconHue(seed));
    });

    test('matrix is horizontally mirrored', () {
      for (var i = 0; i < 50; i++) {
        final matrix = identiconMatrix('user-$i');
        for (final row in matrix) {
          expect(row[0], row[identiconGridSize - 1]);
          expect(row[1], row[identiconGridSize - 2]);
        }
      }
    });

    test('distinct seeds diverge', () {
      final unique = {
        for (var i = 0; i < 200; i++) identiconMatrix('seed-$i').toString(),
      };
      expect(unique.length, greaterThan(180));
    });
  });
}
