// Mocks generated by Mockito 5.4.6 from annotations
// in augo/test/features/chat/services/chat_interaction_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:augo/core/storage/secure_storage_service.dart' as _i18;
import 'package:augo/features/chat/models/chat_message.dart' as _i9;
import 'package:augo/features/chat/models/chat_message_attachment.dart' as _i11;
import 'package:augo/features/chat/models/genui_surface_info.dart' as _i16;
import 'package:augo/features/chat/models/tool_call_info.dart' as _i12;
import 'package:augo/features/chat/repositories/message_repository.dart' as _i8;
import 'package:augo/features/chat/services/custom_content_generator.dart'
    as _i7;
import 'package:augo/features/chat/services/extended_genui_conversation.dart'
    as _i4;
import 'package:augo/features/chat/services/genui_lifecycle_manager.dart'
    as _i13;
import 'package:augo/features/chat/services/genui_service.dart' as _i17;
import 'package:augo/features/chat/state_controllers/stream_state_controller.dart'
    as _i3;
import 'package:augo/features/chat/state_controllers/streaming_controller.dart'
    as _i2;
import 'package:dio/dio.dart' as _i15;
import 'package:flutter/foundation.dart' as _i6;
import 'package:genui/genui.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamingConfig_0 extends _i1.SmartFake
    implements _i2.StreamingConfig {
  _FakeStreamingConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamStateController_1 extends _i1.SmartFake
    implements _i3.StreamStateController {
  _FakeStreamStateController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExtendedGenUiConversation_2 extends _i1.SmartFake
    implements _i4.ExtendedGenUiConversation {
  _FakeExtendedGenUiConversation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenUiHost_3 extends _i1.SmartFake implements _i5.GenUiHost {
  _FakeGenUiHost_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_4<T> extends _i1.SmartFake
    implements _i6.ValueNotifier<T> {
  _FakeValueNotifier_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomContentGenerator_5 extends _i1.SmartFake
    implements _i7.CustomContentGenerator {
  _FakeCustomContentGenerator_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i8.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.OnMessagesChangedCallback get onMessagesChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onMessagesChanged),
            returnValue: (List<_i9.ChatMessage> messages) {},
          )
          as _i8.OnMessagesChangedCallback);

  @override
  _i8.GetCurrentMessagesCallback get getCurrentMessages =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrentMessages),
            returnValue: () => <_i9.ChatMessage>[],
          )
          as _i8.GetCurrentMessagesCallback);

  @override
  _i9.ChatMessage? findById(String? id) =>
      (super.noSuchMethod(Invocation.method(#findById, [id]))
          as _i9.ChatMessage?);

  @override
  int indexOfId(String? id) =>
      (super.noSuchMethod(Invocation.method(#indexOfId, [id]), returnValue: 0)
          as int);

  @override
  String getMessageContent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageContent, [id]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#getMessageContent, [id]),
            ),
          )
          as String);

  @override
  void updateAiMessageState({
    required String? id,
    String? content,
    bool? isTyping,
    _i9.StreamingStatus? streamingStatus,
    DateTime? timestamp,
  }) => super.noSuchMethod(
    Invocation.method(#updateAiMessageState, [], {
      #id: id,
      #content: content,
      #isTyping: isTyping,
      #streamingStatus: streamingStatus,
      #timestamp: timestamp,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateMessageId(String? oldId, String? newId) => super.noSuchMethod(
    Invocation.method(#updateMessageId, [oldId, newId]),
    returnValueForMissingStub: null,
  );

  @override
  bool addSurfaceIdToMessage(
    String? messageId,
    String? surfaceId, {
    String? toolName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addSurfaceIdToMessage,
              [messageId, surfaceId],
              {#toolName: toolName},
            ),
            returnValue: false,
          )
          as bool);

  @override
  bool removeSurfaceIdFromMessage(String? surfaceId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSurfaceIdFromMessage, [surfaceId]),
            returnValue: false,
          )
          as bool);

  @override
  void setAttachmentStatuses({
    required int? messageIndex,
    required Set<String>? attachmentIds,
    required _i11.AttachmentLoadStatus? status,
    String? errorMessage,
  }) => super.noSuchMethod(
    Invocation.method(#setAttachmentStatuses, [], {
      #messageIndex: messageIndex,
      #attachmentIds: attachmentIds,
      #status: status,
      #errorMessage: errorMessage,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void replaceMessageAt(int? index, _i9.ChatMessage? updatedMessage) =>
      super.noSuchMethod(
        Invocation.method(#replaceMessageAt, [index, updatedMessage]),
        returnValueForMissingStub: null,
      );

  @override
  void addMessages(List<_i9.ChatMessage>? newMessages) => super.noSuchMethod(
    Invocation.method(#addMessages, [newMessages]),
    returnValueForMissingStub: null,
  );

  @override
  void setMessages(List<_i9.ChatMessage>? messages) => super.noSuchMethod(
    Invocation.method(#setMessages, [messages]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateFeedbackStatus(
    String? messageId,
    _i9.AIFeedbackStatus? newStatus,
  ) => super.noSuchMethod(
    Invocation.method(#updateFeedbackStatus, [messageId, newStatus]),
    returnValueForMissingStub: null,
  );

  @override
  void addOrUpdateToolCall(String? messageId, _i12.ToolCallInfo? toolCall) =>
      super.noSuchMethod(
        Invocation.method(#addOrUpdateToolCall, [messageId, toolCall]),
        returnValueForMissingStub: null,
      );

  @override
  void cancelPendingToolCalls(String? messageId) => super.noSuchMethod(
    Invocation.method(#cancelPendingToolCalls, [messageId]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GenUiLifecycleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenUiLifecycleManager extends _i1.Mock
    implements _i13.GenUiLifecycleManager {
  MockGenUiLifecycleManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  int get totalSurfacesCreated =>
      (super.noSuchMethod(
            Invocation.getter(#totalSurfacesCreated),
            returnValue: 0,
          )
          as int);

  @override
  int get totalReactiveUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#totalReactiveUpdates),
            returnValue: 0,
          )
          as int);

  @override
  int get totalSurfacesDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#totalSurfacesDeleted),
            returnValue: 0,
          )
          as int);

  @override
  int get activeSurfaceCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSurfaceCount),
            returnValue: 0,
          )
          as int);

  @override
  _i14.Future<void> initialize({_i15.Dio? dio, required String? sseBaseUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #dio: dio,
              #sseBaseUrl: sseBaseUrl,
            }),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void setOnUserMessageSent(void Function(String)? callback) =>
      super.noSuchMethod(
        Invocation.method(#setOnUserMessageSent, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSession() => super.noSuchMethod(
    Invocation.method(#clearSession, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.GenUiSurfaceInfo? getSurfaceInfo(String? surfaceId) =>
      (super.noSuchMethod(Invocation.method(#getSurfaceInfo, [surfaceId]))
          as _i16.GenUiSurfaceInfo?);

  @override
  List<_i16.GenUiSurfaceInfo> getSurfacesForMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfacesForMessage, [messageId]),
            returnValue: <_i16.GenUiSurfaceInfo>[],
          )
          as List<_i16.GenUiSurfaceInfo>);

  @override
  void updateSurfaceStatus(String? surfaceId, _i16.SurfaceStatus? status) =>
      super.noSuchMethod(
        Invocation.method(#updateSurfaceStatus, [surfaceId, status]),
        returnValueForMissingStub: null,
      );

  @override
  void handleDataModelUpdate(String? surfaceId, String? path) =>
      super.noSuchMethod(
        Invocation.method(#handleDataModelUpdate, [surfaceId, path]),
        returnValueForMissingStub: null,
      );

  @override
  void handleDeleteSurface(String? surfaceId) => super.noSuchMethod(
    Invocation.method(#handleDeleteSurface, [surfaceId]),
    returnValueForMissingStub: null,
  );

  @override
  void handleUiRenderEvent(
    String? componentName,
    Map<String, dynamic>? componentData,
    String? uuidV4,
  ) => super.noSuchMethod(
    Invocation.method(#handleUiRenderEvent, [
      componentName,
      componentData,
      uuidV4,
    ]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StreamingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamingController extends _i1.Mock
    implements _i2.StreamingController {
  MockStreamingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StreamingConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeStreamingConfig_0(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i2.StreamingConfig);

  @override
  _i3.StreamStateController get streamState =>
      (super.noSuchMethod(
            Invocation.getter(#streamState),
            returnValue: _FakeStreamStateController_1(
              this,
              Invocation.getter(#streamState),
            ),
          )
          as _i3.StreamStateController);

  @override
  _i2.UpdateMessageStateCallback get onUpdateMessageState =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdateMessageState),
            returnValue:
                ({
                  String? content,
                  required String id,
                  bool? isTyping,
                  _i9.StreamingStatus? streamingStatus,
                }) {},
          )
          as _i2.UpdateMessageStateCallback);

  @override
  _i2.GetCurrentMessageContentCallback get getCurrentMessageContent =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrentMessageContent),
            returnValue: (String messageId) => _i10.dummyValue<String>(
              this,
              Invocation.getter(#getCurrentMessageContent),
            ),
          )
          as _i2.GetCurrentMessageContentCallback);

  @override
  _i2.OnInitialDelayExceededCallback get onInitialDelayExceeded =>
      (super.noSuchMethod(
            Invocation.getter(#onInitialDelayExceeded),
            returnValue: () {},
          )
          as _i2.OnInitialDelayExceededCallback);

  @override
  _i2.OnStreamCompleteCallback get onStreamComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onStreamComplete),
            returnValue: (String? finalTextOverride) {},
          )
          as _i2.OnStreamCompleteCallback);

  @override
  _i2.OnStreamErrorCallback get onStreamError =>
      (super.noSuchMethod(
            Invocation.getter(#onStreamError),
            returnValue: (dynamic error) {},
          )
          as _i2.OnStreamErrorCallback);

  @override
  _i2.OnStreamCancelledCallback get onStreamCancelled =>
      (super.noSuchMethod(
            Invocation.getter(#onStreamCancelled),
            returnValue: (bool hasContent) {},
          )
          as _i2.OnStreamCancelledCallback);

  @override
  String get currentMessageId =>
      (super.noSuchMethod(
            Invocation.getter(#currentMessageId),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#currentMessageId),
            ),
          )
          as String);

  @override
  bool get isStreamDone =>
      (super.noSuchMethod(Invocation.getter(#isStreamDone), returnValue: false)
          as bool);

  @override
  bool get isFirstChunkReceived =>
      (super.noSuchMethod(
            Invocation.getter(#isFirstChunkReceived),
            returnValue: false,
          )
          as bool);

  @override
  bool get isMessageCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isMessageCompleted),
            returnValue: false,
          )
          as bool);

  @override
  bool get isUserCancelled =>
      (super.noSuchMethod(
            Invocation.getter(#isUserCancelled),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasPendingCancel =>
      (super.noSuchMethod(
            Invocation.getter(#hasPendingCancel),
            returnValue: false,
          )
          as bool);

  @override
  void setGenUiService(_i17.GenUiService? service) => super.noSuchMethod(
    Invocation.method(#setGenUiService, [service]),
    returnValueForMissingStub: null,
  );

  @override
  void resetForNewMessage(String? messageId) => super.noSuchMethod(
    Invocation.method(#resetForNewMessage, [messageId]),
    returnValueForMissingStub: null,
  );

  @override
  void startInitialDelayTimer() => super.noSuchMethod(
    Invocation.method(#startInitialDelayTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  bool handleTextChunk(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#handleTextChunk, [text]),
            returnValue: false,
          )
          as bool);

  @override
  void markFirstChunkReceived() => super.noSuchMethod(
    Invocation.method(#markFirstChunkReceived, []),
    returnValueForMissingStub: null,
  );

  @override
  void markMessageCompleted() => super.noSuchMethod(
    Invocation.method(#markMessageCompleted, []),
    returnValueForMissingStub: null,
  );

  @override
  void markStreamEnded({bool? isError = false}) => super.noSuchMethod(
    Invocation.method(#markStreamEnded, [], {#isError: isError}),
    returnValueForMissingStub: null,
  );

  @override
  void handleStreamComplete(String? finalTextOverride) => super.noSuchMethod(
    Invocation.method(#handleStreamComplete, [finalTextOverride]),
    returnValueForMissingStub: null,
  );

  @override
  void handleStreamError(dynamic error) => super.noSuchMethod(
    Invocation.method(#handleStreamError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> cancelPendingOperation({
    required _i14.Future<bool> Function(String)? cancelLastTurn,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelPendingOperation, [], {
              #cancelLastTurn: cancelLastTurn,
              #sessionId: sessionId,
            }),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> waitForPendingCancel() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingCancel, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> cancelStreamAndTimers() =>
      (super.noSuchMethod(
            Invocation.method(#cancelStreamAndTimers, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GenUiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenUiService extends _i1.Mock implements _i17.GenUiService {
  MockGenUiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExtendedGenUiConversation get conversation =>
      (super.noSuchMethod(
            Invocation.getter(#conversation),
            returnValue: _FakeExtendedGenUiConversation_2(
              this,
              Invocation.getter(#conversation),
            ),
          )
          as _i4.ExtendedGenUiConversation);

  @override
  _i5.GenUiHost get manager =>
      (super.noSuchMethod(
            Invocation.getter(#manager),
            returnValue: _FakeGenUiHost_3(this, Invocation.getter(#manager)),
          )
          as _i5.GenUiHost);

  @override
  _i5.GenUiHost get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _FakeGenUiHost_3(this, Invocation.getter(#host)),
          )
          as _i5.GenUiHost);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i14.Future<void> initialize({
    required _i5.Catalog? catalog,
    required _i18.SecureStorageService? storageService,
    required String? sseBaseUrl,
    required void Function(_i5.SurfaceAdded)? onSurfaceAdded,
    required void Function(_i5.SurfaceRemoved)? onSurfaceRemoved,
    required void Function(String)? onTextResponse,
    _i17.OnSessionInit? onSessionInit,
    _i17.OnStreamComplete? onStreamComplete,
    _i17.OnTitleUpdate? onTitleUpdate,
    _i17.OnErrorCallback? onError,
    void Function(String)? onSurfaceIdAdded,
    void Function(Map<String, dynamic>)? onTransactionCreated,
    dynamic configuration,
    _i15.Dio? dio,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #catalog: catalog,
              #storageService: storageService,
              #sseBaseUrl: sseBaseUrl,
              #onSurfaceAdded: onSurfaceAdded,
              #onSurfaceRemoved: onSurfaceRemoved,
              #onTextResponse: onTextResponse,
              #onSessionInit: onSessionInit,
              #onStreamComplete: onStreamComplete,
              #onTitleUpdate: onTitleUpdate,
              #onError: onError,
              #onSurfaceIdAdded: onSurfaceIdAdded,
              #onTransactionCreated: onTransactionCreated,
              #configuration: configuration,
              #dio: dio,
            }),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i6.ValueNotifier<_i5.UiDefinition?> getSurfaceNotifier(String? surfaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfaceNotifier, [surfaceId]),
            returnValue: _FakeValueNotifier_4<_i5.UiDefinition?>(
              this,
              Invocation.method(#getSurfaceNotifier, [surfaceId]),
            ),
          )
          as _i6.ValueNotifier<_i5.UiDefinition?>);

  @override
  void clearSessionToken() => super.noSuchMethod(
    Invocation.method(#clearSessionToken, []),
    returnValueForMissingStub: null,
  );

  @override
  void replayHistoricalSurface({
    required String? surfaceId,
    required String? componentType,
    required Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(#replayHistoricalSurface, [], {
      #surfaceId: surfaceId,
      #componentType: componentType,
      #data: data,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [ExtendedGenUiConversation].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtendedGenUiConversation extends _i1.Mock
    implements _i4.ExtendedGenUiConversation {
  MockExtendedGenUiConversation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomContentGenerator get contentGenerator =>
      (super.noSuchMethod(
            Invocation.getter(#contentGenerator),
            returnValue: _FakeCustomContentGenerator_5(
              this,
              Invocation.getter(#contentGenerator),
            ),
          )
          as _i7.CustomContentGenerator);

  @override
  _i5.GenUiHost get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _FakeGenUiHost_3(this, Invocation.getter(#host)),
          )
          as _i5.GenUiHost);

  @override
  set onUserMessageSent(void Function(String)? callback) => super.noSuchMethod(
    Invocation.setter(#onUserMessageSent, callback),
    returnValueForMissingStub: null,
  );

  @override
  void setSessionId(String? sessionId) => super.noSuchMethod(
    Invocation.method(#setSessionId, [sessionId]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> sendRequest(_i5.ChatMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [message]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> sendRequestWithAttachments(
    String? content, {
    List<Map<String, dynamic>>? attachments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRequestWithAttachments,
              [content],
              {#attachments: attachments},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void cancel() => super.noSuchMethod(
    Invocation.method(#cancel, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSession() => super.noSuchMethod(
    Invocation.method(#clearSession, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
