// Mocks generated by Mockito 5.4.6 from annotations
// in finvo/test/shared/services/exchange_rate_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i2;
import 'package:finvo/core/network/interceptors/business_interceptor.dart'
    as _i5;
import 'package:finvo/core/network/network_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkClient extends _i1.Mock implements _i4.NetworkClient {
  MockNetworkClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.Future<T> request<T>(
    String? path, {
    required _i4.HttpMethod? method,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? data,
    _i5.FromJsonT<T>? fromJsonT,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    bool? enableRetry = true,
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [path],
              {
                #method: method,
                #queryParameters: queryParameters,
                #data: data,
                #fromJsonT: fromJsonT,
                #options: options,
                #cancelToken: cancelToken,
                #enableRetry: enableRetry,
                #maxRetries: maxRetries,
              },
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #request,
                      [path],
                      {
                        #method: method,
                        #queryParameters: queryParameters,
                        #data: data,
                        #fromJsonT: fromJsonT,
                        #options: options,
                        #cancelToken: cancelToken,
                        #enableRetry: enableRetry,
                        #maxRetries: maxRetries,
                      },
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #request,
                    [path],
                    {
                      #method: method,
                      #queryParameters: queryParameters,
                      #data: data,
                      #fromJsonT: fromJsonT,
                      #options: options,
                      #cancelToken: cancelToken,
                      #enableRetry: enableRetry,
                      #maxRetries: maxRetries,
                    },
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<Map<String, dynamic>> requestMap(
    String? path, {
    required _i4.HttpMethod? method,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    bool? enableRetry = true,
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestMap,
              [path],
              {
                #method: method,
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #enableRetry: enableRetry,
                #maxRetries: maxRetries,
              },
            ),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
