// Mocks generated by Mockito 5.4.6 from annotations
// in finvo/test/features/chat/state_controllers/streaming_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i8;
import 'package:finvo/core/storage/secure_storage_service.dart' as _i7;
import 'package:finvo/features/chat/services/extended_genui_conversation.dart'
    as _i2;
import 'package:finvo/features/chat/services/genui_service.dart' as _i5;
import 'package:flutter/foundation.dart' as _i4;
import 'package:genui/genui.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExtendedGenUiConversation_0 extends _i1.SmartFake
    implements _i2.ExtendedGenUiConversation {
  _FakeExtendedGenUiConversation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSurfaceHost_1 extends _i1.SmartFake implements _i3.SurfaceHost {
  _FakeSurfaceHost_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueListenable_2<T> extends _i1.SmartFake
    implements _i4.ValueListenable<T> {
  _FakeValueListenable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GenUiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenUiService extends _i1.Mock implements _i5.GenUiService {
  MockGenUiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExtendedGenUiConversation get conversation =>
      (super.noSuchMethod(
            Invocation.getter(#conversation),
            returnValue: _FakeExtendedGenUiConversation_0(
              this,
              Invocation.getter(#conversation),
            ),
          )
          as _i2.ExtendedGenUiConversation);

  @override
  _i3.SurfaceHost get manager =>
      (super.noSuchMethod(
            Invocation.getter(#manager),
            returnValue: _FakeSurfaceHost_1(this, Invocation.getter(#manager)),
          )
          as _i3.SurfaceHost);

  @override
  _i3.SurfaceHost get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _FakeSurfaceHost_1(this, Invocation.getter(#host)),
          )
          as _i3.SurfaceHost);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Future<void> initialize({
    required _i3.Catalog? catalog,
    required _i7.SecureStorageService? storageService,
    required String? sseBaseUrl,
    required void Function(String)? onSurfaceAdded,
    required void Function(String)? onSurfaceRemoved,
    required void Function(String)? onTextResponse,
    _i5.OnSessionInit? onSessionInit,
    _i5.OnStreamComplete? onStreamComplete,
    _i5.OnTitleUpdate? onTitleUpdate,
    _i5.OnErrorCallback? onError,
    void Function(String)? onSurfaceIdAdded,
    void Function(Map<String, dynamic>)? onTransactionCreated,
    dynamic configuration,
    _i8.Dio? dio,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #catalog: catalog,
              #storageService: storageService,
              #sseBaseUrl: sseBaseUrl,
              #onSurfaceAdded: onSurfaceAdded,
              #onSurfaceRemoved: onSurfaceRemoved,
              #onTextResponse: onTextResponse,
              #onSessionInit: onSessionInit,
              #onStreamComplete: onStreamComplete,
              #onTitleUpdate: onTitleUpdate,
              #onError: onError,
              #onSurfaceIdAdded: onSurfaceIdAdded,
              #onTransactionCreated: onTransactionCreated,
              #configuration: configuration,
              #dio: dio,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i4.ValueListenable<_i3.SurfaceDefinition?> getSurfaceNotifier(
    String? surfaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfaceNotifier, [surfaceId]),
            returnValue: _FakeValueListenable_2<_i3.SurfaceDefinition?>(
              this,
              Invocation.method(#getSurfaceNotifier, [surfaceId]),
            ),
          )
          as _i4.ValueListenable<_i3.SurfaceDefinition?>);

  @override
  void clearSessionToken() => super.noSuchMethod(
    Invocation.method(#clearSessionToken, []),
    returnValueForMissingStub: null,
  );

  @override
  void replayHistoricalSurface({
    required String? surfaceId,
    required String? componentType,
    required Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(#replayHistoricalSurface, [], {
      #surfaceId: surfaceId,
      #componentType: componentType,
      #data: data,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
